export interface IAnime {
    _id: string,
    anim_id: number,
    name: string,
    score: number,
    genres: string,
    english_name: string,
    japanese_name: string,
    synopsis: string,
    type: string,
    episodes: number,
    aired: string,
    premiered: string,
    producers: string,
    licensors: string,
    studios: string,
    source: string,
    duration: string,
    rating: string,
    ranked: number,
    popularity: number,
    members: number,
    favorites: number,
    watching: number,
    completed: number,
    on_Hold: number,
    dropped: number
};